export const DRIZZLE_TRANSACTIONS_REPOSITORY = Symbol('DRIZZLE_TRANSACTIONS_REPOSITORY');
export const PRISMA_TRANSACTIONS_REPOSITORY = Symbol('PRISMA_TRANSACTIONS_REPOSITORY');
export const TRANSACTIONS_REPOSITORY = Symbol('TRANSACTIONS_REPOSITORY');
